blogTitle = "Blog for Damian Mullins"
blogUrl = "http://www.damianmullins.com"
authorName = "Damian Mullins"
authorEmail = "hello@damianmullins.com"
authorBio = "Hi, I'm Damian Mullins, a Senior Web UI Engineer working at Just Eat."
linkPrefix = ""
githubUsername = "DamianMullins"
twitterUsername = "DamianMullins"
linkedInUsername = "damianmullins"
gaCode = "UA-1425869-12"
